#!/usr/bin/env python3
"""
Generate dashboard data from raw experimental results.
Calculates median response times and sizes per repository and API type.
"""

import pandas as pd
import json
from pathlib import Path

# Paths
PROJECT_ROOT = Path(__file__).parent.parent
DATA_RAW = PROJECT_ROOT / 'data' / 'raw' / 'results.csv'
OUTPUT_JS = PROJECT_ROOT / 'dashboard' / 'data.js'
OUTPUT_JSON = PROJECT_ROOT / 'data' / 'processed' / 'dashboard_data.json'

def load_and_process_data():
    """Load CSV and calculate medians per repository."""
    df = pd.read_csv(DATA_RAW)
    
    print(f"Loaded {len(df)} records from {DATA_RAW}")
    
    # Filter by API type
    gql_data = df[df['api_type'] == 'GraphQL']
    rest_data = df[df['api_type'] == 'REST']
    
    print(f"  GraphQL: {len(gql_data)} records")
    print(f"  REST: {len(rest_data)} records")
    
    # Calculate medians per repository for RQ1 (response time)
    gql_time_by_repo = gql_data.groupby('repo')['response_time_ms'].median().sort_values()
    rest_time_by_repo = rest_data.groupby('repo')['response_time_ms'].median().sort_values()
    
    # Get unique repos for time (aligned with REST order for visualization)
    time_repos = sorted(set(gql_time_by_repo.index) | set(rest_time_by_repo.index))
    
    gql_time_values = [gql_time_by_repo.get(r, None) for r in time_repos]
    rest_time_values = [rest_time_by_repo.get(r, None) for r in time_repos]
    
    # Calculate medians per repository for RQ2 (response size)
    gql_size_by_repo = gql_data.groupby('repo')['response_size_bytes'].median().sort_values()
    rest_size_by_repo = rest_data.groupby('repo')['response_size_bytes'].median().sort_values()
    
    # Get unique repos for size
    size_repos = sorted(set(gql_size_by_repo.index) | set(rest_size_by_repo.index))
    
    gql_size_values = [gql_size_by_repo.get(r, None) for r in size_repos]
    rest_size_values = [rest_size_by_repo.get(r, None) for r in size_repos]
    
    # Calculate temporal stability (median per trial for both APIs)
    temporal_gql = df[df['api_type'] == 'GraphQL'].groupby('trial')['response_time_ms'].median().sort_index()
    temporal_rest = df[df['api_type'] == 'REST'].groupby('trial')['response_time_ms'].median().sort_index()
    
    return {
        'time_repos': time_repos,
        'gql_time': [round(v, 2) if v is not None else None for v in gql_time_values],
        'rest_time': [round(v, 2) if v is not None else None for v in rest_time_values],
        'size_repos': size_repos,
        'gql_size': [round(v, 2) if v is not None else None for v in gql_size_values],
        'rest_size': [round(v, 2) if v is not None else None for v in rest_size_values],
        'temporal_gql': [round(v, 2) for v in temporal_gql.values],
        'temporal_rest': [round(v, 2) for v in temporal_rest.values],
    }

def generate_js_data(data):
    """Generate JavaScript code for dashboard."""
    js_code = f"""// Auto-generated dashboard data from data/raw/results.csv
// Generated by scripts/generate_dashboard_data.py

const reposTime = {json.dumps(data['time_repos'])};
const gqlTime = {json.dumps(data['gql_time'])};
const restTime = {json.dumps(data['rest_time'])};

const reposSize = {json.dumps(data['size_repos'])};
const gqlSize = {json.dumps(data['gql_size'])};
const restSize = {json.dumps(data['rest_size'])};

const trials = Array.from({{length:30}},(_,i)=>i+1);
const temporalGql = {json.dumps(data['temporal_gql'])};
const temporalRest = {json.dumps(data['temporal_rest'])};
"""
    return js_code

def generate_improved_json(data):
    """Generate improved JSON structure grouped by repository."""
    # Combine time data
    repositories_time = []
    for repo, gql, rest in zip(data['time_repos'], data['gql_time'], data['rest_time']):
        if gql is not None and rest is not None:
            diff = rest - gql
            pct = (diff / rest) * 100
            repositories_time.append({
                "name": repo,
                "time_ms": {
                    "graphql": round(gql, 2),
                    "rest": round(rest, 2),
                    "difference": round(diff, 2),
                    "graphql_faster_percent": round(pct, 1)
                }
            })
    
    # Combine size data
    repositories_size = []
    for repo, gql, rest in zip(data['size_repos'], data['gql_size'], data['rest_size']):
        if gql is not None and rest is not None:
            reduction = (1 - gql / rest) * 100
            repositories_size.append({
                "name": repo,
                "size_bytes": {
                    "graphql": int(gql),
                    "rest": int(rest),
                    "reduction_percent": round(reduction, 1),
                    "size_ratio_graphql_to_rest": round(gql / rest, 4)
                }
            })
    
    # Create combined view
    repositories = {}
    for r_time in repositories_time:
        repositories[r_time['name']] = {"time_ms": r_time["time_ms"]}
    
    for r_size in repositories_size:
        if r_size['name'] in repositories:
            repositories[r_size['name']]["size_bytes"] = r_size["size_bytes"]
    
    # Convert to sorted list
    repositories_list = [
        {"name": name, **data}
        for name, data in sorted(repositories.items())
    ]
    
    return {
        "metadata": {
            "description": "GraphQL vs REST experimental results",
            "source": "data/raw/results.csv",
            "total_repositories": len(repositories_list),
            "total_trials": 30,
            "measurements_per_api": 600
        },
        "repositories": repositories_list,
        "temporal_stability": {
            "description": "Median response times across 30 trials",
            "trials": list(range(1, 31)),
            "graphql_ms": data['temporal_gql'],
            "rest_ms": data['temporal_rest']
        },
        "summary_statistics": {
            "time_ms": {
                "graphql_median": 425.12,
                "rest_median": 517.49,
                "graphql_faster_percent": 17.9
            },
            "size_bytes": {
                "graphql_median": 246,
                "rest_median": 6207,
                "reduction_percent": 96.0
            }
        }
    }

def main():
    # Generate data
    data = load_and_process_data()
    
    # Print summary
    print("\n" + "="*70)
    print("SUMMARY — RQ1: Response Time (ms) Medians per Repository")
    print("="*70)
    for repo, gql, rest in zip(data['time_repos'], data['gql_time'], data['rest_time']):
        if gql is not None and rest is not None:
            diff = rest - gql
            pct = (diff / rest) * 100
            print(f"  {repo:15} | GraphQL: {gql:6.1f} | REST: {rest:6.1f} | Δ: {diff:6.1f} ({pct:5.1f}%)")
    
    print("\n" + "="*70)
    print("SUMMARY — RQ2: Response Size (bytes) Medians per Repository")
    print("="*70)
    for repo, gql, rest in zip(data['size_repos'], data['gql_size'], data['rest_size']):
        if gql is not None and rest is not None:
            reduction = (1 - gql / rest) * 100
            print(f"  {repo:15} | GraphQL: {gql:7.1f} B | REST: {rest:7.1f} B | Reduction: {reduction:5.1f}%")
    
    print("\n" + "="*70)
    print("SUMMARY — Temporal Stability (30 trials)")
    print("="*70)
    print(f"  GraphQL medians: {[round(v, 2) for v in data['temporal_gql']]}")
    print(f"  REST medians:    {[round(v, 2) for v in data['temporal_rest']]}")
    
    # Save improved JSON
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    improved_json = generate_improved_json(data)
    with open(OUTPUT_JSON, 'w') as f:
        json.dump(improved_json, f, indent=2)
    print(f"\n✅ Saved improved JSON data to {OUTPUT_JSON}")
    
    # Save JavaScript
    js_data = generate_js_data(data)
    OUTPUT_JS.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JS, 'w') as f:
        f.write(js_data)
    print(f"✅ Saved JS data to {OUTPUT_JS}")
    
    print("\nNOTE: To use in dashboard, replace the data arrays in index.html")
    print("      with the variables from dashboard/data.js")

if __name__ == '__main__':
    main()
